const recordStyles = [
    "Pop Rock",
    "House",
    "Vocal",
    "Experimental",
    "Punk",
    "Alternative Rock",
    "Synth-pop",
    "Techno",
    "Indie Rock",
    "Soul",
    "Ambient",
    "Disco",
    "Hardcore",
    "Folk",
    "Country",
    "Ballad",
    "Hard Rock",
    "Electro",
    "Rock & Roll",
    "Chanson",
    "Trance",
    "Romantic",
    "Heavy Metal",
    "Psychedelic Rock",
    "Folk Rock",
    "Soundtrack",
    "Downtempo",
    "Noise",
    "Schlager",
    "Prog Rock",
    "Classic Rock",
    "Funk",
    "Easy Listening",
    "Black Metal",
    "Tech House",
    "Blues Rock",
    "Rhythm & Blues",
    "New Wave",
    "Industrial",
    "Deep House",
    "Classical",
    "Death Metal",
    "Drum n Bass",
    "Progressive House",
    "Euro House",
    "Soft Rock",
    "Garage Rock",
    "Abstract",
    "Gospel",
    "Europop",
    "Minimal",
    "Acoustic",
    "Thrash",
    "Baroque",
    "Modern",
    "Swing",
    "Big Band",
    "Indie Pop",
    "Dub",
    "Country Rock",
    "Drone",
    "Contemporary Jazz",
    "Breakbeat",
    "Progressive Trance",
    "Opera",
    "Holiday",
    "Contemporary",
    "IDM",
    "Dancehall",
    "Breaks",
    "African",
    "Reggae",
    "Dark Ambient",
    "Art Rock",
    "Fusion",
    "Post-Punk",
    "RnB/Swing",
    "Doom Metal",
    "Gangsta",
    "Contemporary R&B",
    "Dance-pop",
    "Religious",
    "Pop Rap",
    "Avantgarde",
    "Beat",
    "Hard Trance",
    "Electro House",
    "Acid",
    "Instrumental",
    "Rockabilly",
    "Jazz-Funk",
    "Score",
    "Comedy",
    "Lo-Fi",
    "Roots Reggae",
    "Theme",
    "Grindcore",
    "Leftfield",
    "Ska",
    "Post Rock",
    "Spoken Word",
    "Soul-Jazz",
    "Dubstep",
    "Psy-Trance",
    "Power Pop",
    "Bolero",
    "Glam",
    "Salsa",
    "New Age",
    "Hip Hop",
    "Bop",
    "Modern Classical",
    "Goth Rock",
    "Conscious",
    "Jazz-Rock",
    "Hard House",
    "Cumbia",
    "Free Improvisation",
    "Emo",
    "J-pop",
    "Musical",
    "Trip Hop",
    "Latin Jazz",
    "Stoner Rock",
    "EBM",
    "Italo-Disco",
    "Volksmusik",
    "Shoegaze",
    "MPB",
    "Surf",
    "Jungle",
    "Hard Bop",
    "Field Recording",
    "Doo Wop",
    "Free Jazz",
    "Story",
    "Hardstyle",
    "Synthwave",
    "Pop Punk",
    "Tango",
    "Oi",
    "Garage House",
    "Samba",
    "Choral",
    "Darkwave",
    "Cool Jazz",
    "Celtic",
    "Radioplay",
    "Post Bop",
    "Bluegrass",
    "Vaporwave",
    "Laïkó",
    "Happy Hardcore",
    "Eurodance",
    "Trap",
    "UK Garage",
    "Tribal",
    "Metalcore",
    "Polka",
    "Novelty",
    "Smooth Jazz",
    "Flamenco",
    "Grunge",
    "Hardcore Hip-Hop",
    "Progressive Metal",
    "Italodance",
    "Dixieland",
    "AOR",
    "Arena Rock",
    "Southern Rock",
    "Symphonic Rock",
    "Nu Metal",
    "Hindustani",
    "Future Jazz",
    "Rumba",
    "Latin",
    "Parody",
    "Kayōkyoku",
    "Boom Bap",
    "Glitch",
    "Harsh Noise Wall",
    "Cha-Cha",
    "Power Metal",
    "Audiobook",
    "Space Rock",
    "Krautrock",
    "Merengue",
    "Dub Techno",
    "Gabber",
    "Bossa Nova",
    "Speed Metal",
    "Neo-Classical",
    "Breakcore",
    "Hi NRG",
    "Jazzy Hip-Hop",
    "Poetry",
    "Thug Rap",
    "Power Electronics",
    "Ranchera",
    "Reggae-Pop",
    "Bollywood",
    "Acid House",
    "Post-Hardcore",
    "Avant-garde Jazz",
    "Boogie",
    "Dungeon Synth",
    "Marches",
    "Renaissance",
    "Musique Concrète",
    "Minimal Techno",
    "Electric Blues",
    "Sludge Metal",
    "Mod",
    "Mambo",
    "Bossanova",
    "Chiptune",
    "Country Blues",
    "Freestyle",
    "Acid Jazz",
    "Bass Music",
    "Nu-Disco",
    "Interview",
    "Tribal House",
    "Big Beat",
    "Berlin-School",
    "Math Rock",
    "Indian Classical",
    "Calypso",
    "Modal",
    "Light Music",
    "Chicago Blues",
    "Broken Beat",
    "Psychedelic",
    "Rocksteady",
    "Neofolk",
    "Education",
    "Ethereal",
    "Neo Soul",
    "Impressionist",
    "Crust",
    "Afrobeat",
    "Mandopop",
    "Afro-Cuban",
    "Operetta",
    "Guaracha",
    "Britpop",
    "Lounge",
    "Grime",
    "Chillwave",
    "Video Game Music",
    "G-Funk",
    "Hip-House",
    "Ragtime",
    "Éntekhno",
    "Goa Trance",
    "Canzone Napoletana",
    "Euro-Disco",
    "Melodic Death Metal",
    "Lovers Rock",
    "Gothic Metal",
    "Goregrind",
    "Brass Band",
    "Nursery Rhymes",
    "Deep Techno",
    "Psychobilly",
    "Symphonic Metal",
    "Rhythmic Noise",
    "Neo-Romantic",
    "Dialogue",
    "Tech Trance",
    "Medieval",
    "Son",
    "Cut-up/DJ",
    "Dream Pop",
    "Pacific",
    "Hard Techno",
    "Atmospheric Black Metal",
    "Speedcore",
    "Ragga",
    "Twist",
    "Guaguancó",
    "Promotional",
    "Nordic",
    "Military",
    "K-pop",
    "Honky Tonk",
    "Ragga HipHop",
    "Educational",
    "Space-Age",
    "Eurobeat",
    "New Jack Swing",
    "Fado",
    "Melodic Hardcore",
    "Organ",
    "Mariachi",
    "Funk Metal",
    "Political",
    "Deathcore",
    "Music Hall",
    "Acid Rock",
    "Romani",
    "Sound Collage",
    "Hawaiian",
    "Highlife",
    "Soukous",
    "Soca",
    "Folk Metal",
    "Makina",
    "Reggaeton",
    "Zouk",
    "Afro-Cuban Jazz",
    "Freetekno",
    "City Pop",
    "Speech",
    "Witch House",
    "Monolog",
    "Anison",
    "Jazzdance",
    "Noisecore",
    "Horrorcore",
    "Hands Up",
    "J-Rock",
    "Piano Blues",
    "Post-Metal",
    "Delta Blues",
    "Modern Electric Blues",
    "Vallenato",
    "Coldwave",
    "Cubano",
    "Public Broadcast",
    "Bubblegum",
    "Norteño",
    "Luk Thung",
    "New Beat",
    "Electroacoustic",
    "Forró",
    "Gypsy Jazz",
    "Italo House",
    "Corrido",
    "Bhangra",
    "Viking Metal",
    "Enka",
    "No Wave",
    "Sound Art",
    "Jumpstyle",
    "Harmonica Blues",
    "Therapy",
    "Texas Blues",
    "Boogaloo",
    "Porro",
    "Special Effects",
    "Cajun",
    "Speed Garage",
    "Pub Rock",
    "Oratorio",
    "Yé-Yé",
    "Post-Modern",
    "Industrial Metal",
    "Tejano",
    "Cloud Rap",
    "P.Funk",
    "Alternative Metal",
    "Jump Blues",
    "Hillbilly",
    "Depressive Black Metal",
    "Karaoke",
    "Andean Music",
    "Alt-Pop",
    "Illbient",
    "Noise Rock",
    "Power Violence",
    "Pachanga",
    "Bassline",
    "Rebetiko",
    "Descarga",
    "Technical Death Metal",
    "Guajira",
    "Boogie Woogie",
    "Groove Metal",
    "Beguine",
    "Cantopop",
    "Donk",
    "Screw",
    "Louisiana Blues",
    "Raï",
    "Son Montuno",
    "Chinese Classical",
    "Deathrock",
    "Min'yō",
    "Nueva Cancion",
    "Séga",
    "Charanga",
    "Russian Pop",
    "Western Swing",
    "Copla",
    "Hokkien Pop",
    "Juke",
    "Klezmer",
    "Horror Rock",
    "Sermon",
    "Crunk",
    "Jangle Pop",
    "Aboriginal",
    "Compas",
    "Technical",
    "Pasodoble",
    "Latin Pop",
    "Catalan Music",
    "Levenslied",
    "DJ Battle Tool",
    "Carnatic",
    "Disco Polo",
    "Electroclash",
    "Tropical House",
    "Bachata",
    "Appalachian Music",
    "Ghetto",
    "Health-Fitness",
    "Népzene",
    "Conjunto",
    "Danzon",
    "Funeral Doom Metal",
    "Ethno-pop",
    "Música Criolla",
    "Progressive Breaks",
    "Turntablism",
    "Swingbeat",
    "Halftime",
    "Minneapolis Sound",
    "Batucada",
    "Zydeco",
    "Pornogrind",
    "Sea Shanties",
    "Bounce",
    "Bayou Funk",
    "Musette",
    "Free Funk",
    "Indo-Pop",
    "Bakersfield Sound",
    "Quechua",
    "Huayno",
    "Footwork",
    "Liscio",
    "Balearic",
    "J-Core",
    "Steel Band",
    "Lambada",
    "Swamp Pop",
    "Cretan",
    "Early",
    "Go-Go",
    "Sound Poetry",
    "Baião",
    "Movie Effects",
    "Skiffle",
    "Doomcore",
    "Axé",
    "Schranz",
    "Choro",
    "Ghetto House",
    "Pipe & Drum",
    "Dark Electro",
    "Glitch Hop",
    "Miami Bass",
    "Plena",
    "Bleep",
    "Ghazal",
    "Gamelan",
    "Zarzuela",
    "Kwaito",
    "Erotic",
    "Mizrahi",
    "Kolo",
    "Persian Classical",
    "Cabaret",
    "Ottoman Classical",
    "Hyperpop",
    "Samba-Canção",
    "Plunderphonics",
    "Zamba",
    "Chamamé",
    "Nueva Trova",
    "Unblack Metal",
    "Ryūkōka",
    "Trova",
    "NDW",
    "Basque Music",
    "Barbershop",
    "Bengali Music",
    "Ballet",
    "Chacarera",
    "Britcore",
    "Gaita",
    "Mo Lam",
    "Baroque Pop",
    "UK Street Soul",
    "Sertanejo",
    "Blackgaze",
    "Public Service Announcement",
    "Phonk",
    "Future House",
    "Group Sounds",
    "Exotica",
    "Rock Opera",
    "Dangdut",
    "Spirituals",
    "Neo Trance",
    "Chutney",
    "Crossover thrash",
    "Memphis Blues",
    "Beatdown",
    "K-Rock",
    "Occitan",
    "Ghettotech",
    "Reggae Gospel",
    "Qawwali",
    "Joropo",
    "Tamil Film Music",
    "East Coast Blues",
    "Sunshine Pop",
    "Twelve-tone",
    "Luk Krung",
    "Favela Funk",
    "Future Bass",
    "Nhạc Vàng",
    "Marimba",
    "Gusle",
    "Villancicos",
    "Kaseko",
    "Drill",
    "Timba",
    "Keroncong",
    "Hyphy",
    "Andalusian Classical",
    "Dub Poetry",
    "Banda",
    "UK Funky",
    "Guarania",
    "Morna",
    "Dark Jazz",
    "Hiplife",
    "Piedmont Blues",
    "Slowcore",
    "Cape Jazz",
    "Maloya",
    "Medical",
    "Overtone Singing",
    "Toasting",
    "Baltimore Club",
    "Jibaro",
    "Mento",
    "Ambient House",
    "Electro Swing",
    "Sephardic",
    "Jota",
    "Izvorna",
    "Milonga",
    "Vaudeville",
    "Lento Violento",
    "Salegy",
    "Galician Traditional",
    "Marcha Carnavalesca",
    "Deconstructed Club",
    "Caipira",
    "Griot",
    "Mathcore",
    "Bomba",
    "Phleng Phuea Chiwit",
    "French House",
    "Hard Beat",
    "Comfy Synth",
    "Mbalax",
    "Zemer Ivri",
    "Candombe",
    "Beatbox",
    "Jersey Club",
    "Post-Grunge",
    "Shidaiqu",
    "Aguinaldo",
    "Serial",
    "Thai Classical",
    "Mugham",
    "Nerdcore Techno",
    "Stride",
    "Gagaku",
    "Ballroom",
    "Bambuco",
    "Funaná",
    "Champeta",
    "Cantorial",
    "Shaabi",
    "Cuatro",
    "Skweee",
    "Carimbó",
    "Sámi Music",
    "Seresta",
    "Hypnagogic pop",
    "Kizomba",
    "Sonero",
    "Jug Band",
    "Philippine Classical",
    "Occult",
    "Gwo Ka",
    "Moombahton",
    "Break-In",
    "Microhouse",
    "Funkot",
    "Geet",
    "Yemenite Jewish",
    "Future Pop",
    "Progressive Bluegrass",
    "Cobla",
    "Waiata",
    "Frevo",
    "Mouth Music",
    "Junkanoo",
    "Néo Kyma",
    "Hyper Techno",
    "Hill Country Blues",
    "Rune Singing",
    "Taarab",
    "Korean Court Music",
    "Filk",
    "Bitpop",
    "Piobaireachd",
    "Rapso",
    "Low Bap",
    "Lowercase",
    "V-pop",
    "Bubbling",
    "Cambodian Classical",
    "Kuduro",
    "Gqom",
    "Zhongguo Feng",
    "Guggenmusik",
    "Neopagan",
    "Rōkyoku",
    "Amapiano",
    "Lao Music",
    "Klasik",
    "Bangladeshi Classical",
    "Nintendocore",
    "Għana",
    "Sean-nós",
    "Bongo Flava",
    "Currulao",
    "Motswako",
    "Brit Pop",
    "Spaza",
    "Azonto",
    "Trallalero",
    "Jiuta",
    "Honkyoku",
    "Sokyoku",
    "Shomyo",
    "Singeli",
    "Ojkača",
    "Sankyoku",
    "Shinkyoku",
    "Shoegazer",
    "Gogo",
];

export default recordStyles;
