const recordCountries = [
    "US",
    "UK",
    "Germany",
    "France",
    "Japan",
    "Italy",
    "Europe",
    "Canada",
    "Unknown",
    "Netherlands",
    "Spain",
    "Australia",
    "Russia",
    "Brazil",
    "Sweden",
    "Belgium",
    "Greece",
    "Poland",
    "Mexico",
    "Finland",
    "Jamaica",
    "Switzerland",
    "Worldwide",
    "USSR",
    "Argentina",
    "Denmark",
    "Portugal",
    "Norway",
    "Austria",
    "New Zealand",
    "UK & Europe",
    "South Africa",
    "Colombia",
    "Yugoslavia",
    "Hungary",
    "USA & Canada",
    "India",
    "Ukraine",
    "Turkey",
    "Czech Republic",
    "Romania",
    "Czechoslovakia",
    "Indonesia",
    "Ireland",
    "Venezuela",
    "Taiwan",
    "South Korea",
    "Chile",
    "Peru",
    "Israel",
    "Bulgaria",
    "Thailand",
    "Malaysia",
    "Scandinavia",
    "China",
    "German Democratic Republic (GDR)",
    "Hong Kong",
    "Philippines",
    "Croatia",
    "USA & Europe",
    "Ecuador",
    "Serbia",
    "Lithuania",
    "Germany, Austria, & Switzerland",
    "UK, Europe & US",
    "Singapore",
    "Slovenia",
    "Slovakia",
    "Uruguay",
    "Iceland",
    "Bolivia",
    "Australasia",
    "UK & Ireland",
    "Australia & New Zealand",
    "Nigeria",
    "Estonia",
    "USA, Canada & Europe",
    "Benelux",
    "Lebanon",
    "Panama",
    "UK & US",
    "Costa Rica",
    "Pakistan",
    "Cuba",
    "Egypt",
    "Latvia",
    "Middle East",
    "Puerto Rico",
    "Kenya",
    "Iran",
    "Belarus",
    "Morocco",
    "Guatemala",
    "Saudi Arabia",
    "Barbados",
    "Trinidad & Tobago",
    "Macedonia",
    "Czech Republic & Slovakia",
    "Bosnia & Herzegovina",
    "Luxembourg",
    "USA, Canada & UK",
    "Algeria",
    "Zimbabwe",
    "Singapore, Malaysia & Hong Kong",
    "Ghana",
    "Madagascar",
    "El Salvador",
    "North America (inc Mexico)",
    "Dominican Republic",
    "Congo, Democratic Republic of the",
    "Reunion",
    "Ivory Coast",
    "France & Benelux",
    "Tunisia",
    "United Arab Emirates",
    "Zaire",
    "Angola",
    "Serbia and Montenegro",
    "Georgia",
    "Malta",
    "Germany & Switzerland",
    "Asia",
    "Rhodesia",
    "Cyprus",
    "Mozambique",
    "Singapore & Malaysia",
    "Mauritius",
    "Zambia",
    "Syria",
    "Azerbaijan",
    "Kazakhstan",
    "Nicaragua",
    "Paraguay",
    "Senegal",
    "Ethiopia",
    "Vietnam",
    "Guadeloupe",
    "Moldova, Republic of",
    "Russia & CIS",
    "UK & France",
    "South Vietnam",
    "Bahamas, The",
    "Suriname",
    "UK, Europe & Japan",
    "Haiti",
    "Gulf Cooperation Council",
    "Faroe Islands",
    "South America",
    "Cameroon",
    "South East Asia",
    "Albania",
    "Uzbekistan",
    "Honduras",
    "Kuwait",
    "Martinique",
    "Benin",
    "Sri Lanka",
    "Curaçao",
    "Armenia",
    "Andorra",
    "Netherlands Antilles",
    "Mali",
    "Liechtenstein",
    "Congo, Republic of the",
    "Sudan",
    "Dahomey",
    "Guinea",
    "Uganda",
    "Burma",
    "Mongolia",
    "French Polynesia",
    "Nepal",
    "Kosovo",
    "Cambodia",
    "Greenland",
    "Virgin Islands",
    "North Korea",
    "Austria-Hungary",
    "Bangladesh",
    "Iraq",
    "Dutch East Indies",
    "Southern Rhodesia",
    "Bermuda",
    "Cape Verde",
    "Isle Of Man",
    "Guyana",
    "UK & Germany",
    "Seychelles",
    "Tanzania",
    "Bahrain",
    "Central America",
    "Libya",
    "Montenegro",
    "Jordan",
    "Palestine",
    "Belgian Congo",
    "Singapore, Malaysia, Hong Kong & Thailand",
    "Gabon",
    "Monaco",
    "Afghanistan",
    "Togo",
    "Belize",
    "Cayman Islands",
    "Fiji",
    "Yemen",
    "New Caledonia",
    "Papua New Guinea",
    "Aruba",
    "French Guiana",
    "North & South America",
    "Laos",
    "Upper Volta",
    "East Timor",
    "Dominica",
    "San Marino",
    "Africa",
    "Burkina Faso",
    "Namibia",
    "UK, Europe & Israel",
    "Sierra Leone",
    "Kyrgyzstan",
    "Brunei",
    "Turkmenistan",
    "Eritrea",
    "Ottoman Empire",
    "Jersey",
    "Guernsey",
    "Botswana",
    "Saint Kitts and Nevis",
    "Guam",
    "Central African Republic",
    "Korea (pre-1945)",
    "Qatar",
    "Somalia",
    "Liberia",
    "Sint Maarten",
    "Grenada",
    "Macau",
    "Saint Lucia",
    "Protectorate of Bohemia and Moravia",
    "Bhutan",
    "Indochina",
    "Maldives",
    "Guinea-Bissau",
    "Niger",
    "Gambia, The",
    "Lesotho",
    "Saint Vincent and the Grenadines",
    "Malawi",
    "Cook Islands",
    "Comoros",
    "Gibraltar",
    "Palau",
    "Vatican City",
    "Bohemia",
    "Rwanda",
    "Oman",
    "Samoa",
    "Tajikistan",
    "Abkhazia",
    "British Virgin Islands",
    "Hong Kong & Thailand",
    "Mayotte",
    "South Pacific",
    "Anguilla",
    "Mauritania",
    "Zanzibar",
    "Djibouti",
    "Montserrat",
    "Sao Tome and Principe",
    "South West Africa",
    "Vanuatu",
    "Norfolk Island",
    "Tonga",
    "Solomon Islands",
    "Swaziland",
    "West Bank",
    "Marshall Islands",
    "Turks and Caicos Islands",
    "American Samoa",
    "Antarctica",
    "Antigua & Barbuda",
    "Northern Mariana Islands",
    "Southern Sudan",
    "Equatorial Guinea",
    "Kiribati",
    "Chad",
    "Falkland Islands",
    "Gaza Strip",
    "Korea",
    "Man, Isle of",
    "Nauru",
    "Niue",
    "Pitcairn Islands",
    "Saint Pierre and Miquelon",
    "Tibet",
    "Tuvalu",
    "Wallis and Futuna",
];

export default recordCountries;
