export const recordFormats = [
    "Vinyl",
    "Album",
    "CD",
    "LP",
    '7"',
    "45 RPM",
    "Single",
    "File",
    "Compilation",
    "Stereo",
    "Cassette",
    '12"',
    "MP3",
    "Reissue",
    "Promo",
    "EP",
    "Limited Edition",
    "CDr",
    "33 ⅓ RPM",
    "Mono",
    '10"',
    "Unofficial Release",
    "78 RPM",
    "Shellac",
    "FLAC",
    "Remastered",
    "WAV",
    "Numbered",
    "Maxi-Single",
    "Repress",
    "AAC",
    "White Label",
    "Single Sided",
    "Mixed",
    "DVD",
    "Test Pressing",
    "DVD-Video",
    "Club Edition",
    "Box Set",
    "Mini-Album",
    "Enhanced",
    "Sampler",
    "NTSC",
    "All Media",
    "Special Edition",
    "PAL",
    "Deluxe Edition",
    "Styrene",
    "AIFF",
    "8-Track Cartridge",
    "Mini",
    "Mixtape",
    "Flexi-disc",
    "CD-ROM",
    "Picture Disc",
    "VHS",
    "Advance",
    "ALAC",
    "Misprint",
    "Multichannel",
    "Lathe Cut",
    "Copy Protected",
    "Acetate",
    "Transcription",
    "DVDr",
    "Jukebox",
    "ogg-vorbis",
    "Partially Mixed",
    "HDCD",
    "Reel-To-Reel",
    "SACD",
    "Record Store Day",
    "Hybrid",
    '8"',
    "Shape",
    "Blu-ray",
    "Etched",
    "Mispress",
    "Quadraphonic",
    "4-Track Stereo",
    '¼"',
    '7" Cine Reel',
    "7 ½ ips",
    '6"',
    "Card Backed",
    "Laserdisc",
    '5½"',
    "Partially Unofficial",
    "Betacam SP",
    "VCD",
    "MPEG-4 Video",
    "80 RPM",
    "Memory Stick",
    "3 ¾ ips",
    "Cylinder",
    '5"',
    '3.5"',
    "Minidisc",
    "Minimax",
    "Edison Disc",
    "Pathé Disc",
    "Floppy Disk",
    "4 Minute",
    "DVD-Audio",
    "MP3 Surround",
    "SECAM",
    "2 Minute",
    "WMA",
    '16"',
    '9"',
    "Business Card",
    "2-Track Stereo",
    "Special Cut",
    "4-Track Cartridge",
    '4"',
    '5" Cine Reel',
    '11"',
    "Tour Recording",
    "DVD-Data",
    "CD+G",
    "Blu-ray Audio",
    "Double Sided",
    "U-matic",
    "Blu-ray-R",
    '6½"',
    "29cm",
    "DCC",
    "WMV",
    "DualDisc",
    "16 ⅔ RPM",
    "Ambisonic",
    "2-Track Mono",
    "15 ips",
    "XRCD",
    "CDV",
    '5.25"',
    "Betamax",
    "27cm",
    "90 RPM",
    "AVCD",
    '10.5" NAB Reel',
    "8 ⅓ RPM",
    '3"',
    "DAT",
    "25cm",
    "MOV",
    "PlayTape",
    "CDi",
    "DSF",
    "Microcassette",
    "MPEG Video",
    "MiniDV",
    '2"',
    "Bioplastic",
    "SHN",
    "Tefifon",
    "AIFC",
    "21cm",
    "AVI",
    '3½"',
    "4-Track Mono",
    "VHD",
    "Ultra HD Blu-ray",
    "DVDplus",
    "4K",
    "SelectaVision",
    "Opus",
    "UMD",
    "Pocket Rocker",
    "CD-Record",
    "HD DVD",
    "Super VHS",
    "Video8",
    "Mighty Tiny",
    "35cm",
    "15/16 ips",
    "VinylDisc",
    '3" Cine Reel',
    "FLV",
    "Betacam",
    "SVCD",
    "SWF",
    "AMR",
    '½"',
    "3 Minute",
    "Disc Image",
    "HitClips",
    "MP2",
    "WavPack",
    "Film Reel",
    '1"',
    "Revere Magnetic Stereo Tape Ca",
    "Concert",
    "Salon",
    "Elcaset",
    "Video 2000",
    "Zip Disk",
    '6" Cine Reel',
    "RCA Tape Cartridge",
    "RM",
    '⅛"',
    "120 RPM",
    "35mm",
    "DFF",
    "30 ips",
    "50cm",
    "HD DVD-R",
    "Sopic",
    "1 ⅞ ips",
    "Dolby 5.1",
    "NT Cassette",
    "16mm",
    "RA",
    "Sabamobil",
    "40cm",
    "Wire Recording",
    "APE",
    "Cartrivision",
    "CD-Text",
    "DC-International",
    "None",
    "TeD",
    "12",
    "DVD-9",
    "MPEG-4",
    "MVD",
    "TTA",
];
